language: objective-c
osx_image: xcode8.3
before_install:
- curl -sSL https://get.rvm.io | bash -s stable 
- source ~/.bashrc    
- source ~/.bash_profile
# - rvm install 2.3.0
# install:
  
# - ruby -v    
# - rvm reload   
# - rvm reinstall ruby-2.3.0
# - ruby -v 
# xcode_project: TravisCI_Demo_OC.xcodeproj # path to your xcodeproj folder
# xcode_scheme: TravisCI_Demo_OCTests
script: 
    set -o pipefail
    xcodebuild clean test -project Tests/UnitTests.xcodeproj -scheme UnitTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest'